### ISSUE TITLE
Please extract data about Dhaka city too

### ISSUE THREAD

**Issue by KhanShaheb34** [ahmedsadman/covid19-bd#1]
Hi,
I'd been trying to build a COVID-19 Dashboard for Bangladesh. But, I couldn't extract data from the pdf given in the IEDCR website. Then I saw your repository, and thanks to you I could build a dashboard.
Please have a look at it [here](https://www.co-ronabd.info/), GitHub repo is [here](https://github.com/KhanShaheb34/nCov19-InteractiveDashboard-BD).

Now, I'm trying to build a dashboard for Dhaka city too. But, again having trouble extracting data from the PDF.
So, can you please extract data about Dhaka city and serve it in a different route?

**Comment by ahmedsadman** [comment]
Yes, I have that feature in mind. But the problem is, the IEDCR guys change the Dhaka area-wise data format very frequently than expected (the format for district data changes too, but I was able to generalize them in a common pattern). So I am finding it a bit difficult to cope. Stay Tuned

**Comment by KhanShaheb34** [comment]
Ok. 😊
