### ISSUE TITLE
Return remaining districts with count 0

### ISSUE THREAD

**Issue by shunjid** [ahmedsadman/covid19-bd#3]
In client-side, I've been dealing with the id's you're providing for each district. Now, there are some districts which aren't affected yet. It would be great if you:

- Return those districts with count = 0
```json
    {
      "count": 0,
      "id": 60,
      "name": "Bhola",
      "prev_count": 0
    },
```

**Comment by ahmedsadman** [comment]
Things like this should be handled from the frontend side. Also, don't depend on the ID because IEDCR changes data formatting frequently and I also have to make changes to the database which can in turn change district ids.

**Comment by shunjid** [comment]
Thanks, for informing about this.
