### ISSUE TITLE
Stats isn't updating for lack of recovery data

### ISSUE THREAD

**Issue by KhanShaheb34** [ahmedsadman/covid19-bd#4]
API is providing the data from two days ago.
Please fix the bug.

**Comment by ahmedsadman** [comment]
Yes, I noticed the bug yesterday because IEDCR changed some formatting. They removed the "Recovered" section. I am still waiting for them to know if the change is permanent from them. According to that, I will fix that as soon as possible.

**Comment by ahmedsadman** [comment]
Fixed with da2e7519dfb619889d79585158a31c0abb49f637. Recovery data no longer available

**Comment by KhanShaheb34** [comment]
Although they removed recovered field from their website, they're publishing the recovery data on their video conferences. So, there must be any other source, who is keeping track of the data. I'll let you know if I get to find one.

**Comment by KhanShaheb34** [comment]
@ahmedsadman , can you pull the recovery data from here: https://github.com/pomber/covid19

**Comment by ahmedsadman** [comment]
I know about several APIs that can provide worldwide data. But I need some time. I am thinking of changing the data source to some other platforms rather than IEDCR, because they provide updates faster. This has more priority. As other API's are already available for worldwide data, I will integrate recovery counts later

**Comment by ahmedsadman** [comment]
The Timeseries data you provided is suddenly showing all counts as 0. Also, if you know about any source that is providing Recovery data for the last 24 hours, please let me know. @KhanShaheb34

**Comment by KhanShaheb34** [comment]
[corona.gov.bd](https://corona.gov.bd/) shows recovery data of last 24 hours.

**Comment by ahmedsadman** [comment]
Yes, but they provide it in Bangla. It will only work if I can replace Unicode digits with English digits. I will look into that, but I am not sure if that would work 100% foolproof.

**Comment by KhanShaheb34** [comment]
That's great news. :smiley: Best of luck to you for implementing that.

**Comment by ahmedsadman** [comment]
Closing with 9fd7c06b0cefb177fa34e64de8c303f42a413e01. Recovery stats now available

**Comment by KhanShaheb34** [comment]
Great Job.. :grin: Thank you..
