### ISSUE TITLE
District data isn't updating

### ISSUE THREAD

**Issue by KhanShaheb34** [ahmedsadman/covid19-bd#6]
IEDCR is now publishing the google spreadsheet of the data. I think that's the reason why data isn't updating. Please have a look.

**Comment by KhanShaheb34** [comment]
@ahmedsadman, also the stat data isn't updating...

**Comment by ahmedsadman** [comment]
Yes, you're right. They are providing the data in a different form now. I will look into it but it will take some time.

**Comment by KhanShaheb34** [comment]
Is the problem fixed now?

**Comment by ahmedsadman** [comment]
> Is the problem fixed now?
Yes, it is fixed and is working. I will keep it on test for a few days and close the issue if everything works fine.

**Comment by KhanShaheb34** [comment]
OK.. Then I'm going to restore my website.. 😀

**Comment by ahmedsadman** [comment]
This is now fixed
