### ISSUE TITLE
The API is offline

### ISSUE THREAD

**Issue by KhanShaheb34** [ahmedsadman/covid19-bd#9]
The API is offline for maintenance for a long time. Did you discontinue the project?

**Comment by KhanShaheb34** [comment]
Hi @ahmedsadman, did you check where's the problem?

**Comment by ahmedsadman** [comment]
The govt doesn't update district-wise data regularly, which was the core feature of the API. And I currently don't have free time to maintain the projects. Thus, it is discontinued.

**Comment by KhanShaheb34** [comment]
Ok 😊
